### ISSUE TITLE
ID Required to Create Webhook/Rule

### ISSUE THREAD

**Issue by dolendupes** [codatio/client-sdk-typescript#180]
https://github.com/codatio/client-sdk-typescript/blob/1ca8d4204ecf2a0688189f3a1ca207773991efc0/common/src/sdk/webhooks.ts#L28

The request object to create a webhook/rule is the shared.rule object which has 'id' as required'. This doesn't make sense since the id should be generated by codat.

**Comment by dcoplowe** [comment]
Hi dleondupes,

Thank you for raising this. We have looked into this and separated out the create and get models. This should make it easier to work with. 

Let me know if you have any other questions.

Many thanks,

David

**Comment by dolendupes** [comment]
Thanks @dcoplowe.  Solution works for me.
