### ISSUE TITLE
Shared.ErrorMessage/Schema Consistency

### ISSUE THREAD

**Issue by dolendupes** [codatio/client-sdk-typescript#183]
Http Statuses are mapped to different objects when returned from accounting vs common.  Accounting uses shared.Schema and common uses shared.ErrorMessage. They should be consistent and I'm guessing they should both be shared.ErrorMessage.

https://github.com/codatio/client-sdk-typescript/blob/42ff79f86eda6860ef5314917e4bfcaf1c804945/accounting/src/sdk/models/shared/schema.ts#L11

https://github.com/codatio/client-sdk-typescript/blob/42ff79f86eda6860ef5314917e4bfcaf1c804945/common/src/sdk/models/shared/errormessage.ts#L11

**Comment by dcoplowe** [comment]
Hi dolendupes,

Thank you for raising this. I will take a look and hopefully get a fix out soon. I will keep you updated on this.

Many thanks,

David

**Comment by dcoplowe** [comment]
Hi dolendupes,

We have released a fix for this so please bump to the latest version.

Many thanks,

David

**Comment by dolendupes** [comment]
This looks good! Thanks @dcoplowe
