### ISSUE TITLE
Allow for Defaulting of Retry Strategy

### ISSUE THREAD

**Issue by dolendupes** [codatio/client-sdk-typescript#185]
We would like to default our retry strategy to a "none" strategy for all data types. I could see a couple of alternative solutions for this:

1) The sdkConfiguration would allow for us to provide a default retry strategy
2) The default strategy is 'none' rather than an exponential backoff
3) Both 1 and 2

Roughly speaking the code would be below and in CodatCommon in a similar place.

https://github.com/codatio/client-sdk-typescript/blob/22eb5e7441f6f81c5580222871966ee3d7d5b763/accounting/src/sdk/sdk.ts#L69

**Comment by dolendupes** [comment]
Wanted to see if anyone had a chance to look at this. Would it help if I put in a pull request?

**Comment by dcoplowe** [comment]
Hi @dolendupes,

I've shared your feedback with our vendor and they are looking to add this to their roadmap. I'll keep you posted once we have an idea of when global retry override will be released. 

Many thanks,

David

**Comment by dolendupes** [comment]
> eedback with our vendor and they are looking to add this to their roadmap. I'll keep you posted once we have an idea of when global retry override will be released.

We can definitely work around. It's mainly that our default strategy is going to be a "no-retry" and having to override this in every command call is not ideal.

**Comment by dcoplowe** [comment]
Agreed, this isn't ideal. I'll let you know when the vendor has released their update.

**Comment by dcoplowe** [comment]
Hi @dolendupes,

We wanted to let you know that support for global retry overrides is now live! Feel free to explore and utilize it in your projects. Should you need any assistance or have questions, please don't hesitate to reach out.

Many thanks,

David

**Comment by dolendupes** [comment]
Saw this come in. We are implementing now...thanks for getting it in.
