### ISSUE TITLE
Accounting SDK (Previous) - Account Supplemental Data

### ISSUE THREAD

**Issue by dolendupes** [codatio/client-sdk-typescript#442]
The Codat API supports supplemental data for the Account data type. However, the Accounting SDK does not have the supplemental data field https://github.com/codatio/client-sdk-typescript/blob/main/previous-versions/accounting/src/sdk/models/shared/account.ts.

**Comment by dcoplowe** [comment]
Hi @dolendupes,

Thank you for raising. We are looking into this.

Many thanks,

David
