### ISSUE TITLE
Creating a customer on Xero returns validation error

### ISSUE THREAD

**Issue by alexpchin** [codatio/client-sdk-typescript#476]
When creating a customer with the @codat/accounting-api, we are getting an error:

```
Error: Status code: BadRequest and content: {
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements": [
    {
      "ContactID": "00000000-0000-0000-0000-000000000000",
      "ContactStatus": "ACTIVE",
      "Name": "AlexUnique2 Chin",
      "FirstName": "AlexUnique2",
      "LastName": "Chin",
      "EmailAddress": "[alex+unique2@gobunk.co.uk](mailto:alex+unique2@gobunk.co.uk)",
      "Addresses": [],
      "Phones": [],
      "UpdatedDateUTC": "\/Date(1698943235833)\/",
      "ContactGroups": [],
      "IsSupplier": false,
      "IsCustomer": true,
      "ContactPersons": [],
      "HasAttachments": false,
      "HasValidationErrors": true,
      "ValidationErrors": [
        {
          "Message": "The contact name AlexUnique2 Chin is already assigned to another contact. The contact name must be unique across all active contacts."
        }
      ]
    }
  ]
}
```

Codat support have said:

Based on the platforms creation time (2023-11-02 16:40:20) this record looks to have been created within the UI just prior to our receiving the request to push the contact at 2023-11-02 16:40:35.0718695. Additionally, our provided error response is based off of the response returned from Xero as shown below. 

However, we aren't creating users via the UI at all, only via the API and we have tested a number of new contacts with unique contact names and emails.

We have even put a retry when the webhook returns a failure which tries to get the Customer, but no customers are found. We then tried to do a sync of customers before this retry, but still no dice. 

Any ideas?

We've upgraded to 0.36.0.

**Comment by alexpchin** [comment]
Could it have anything to do with some sort of retry / preflight request that is creating the customer before the main request actually completes?

**Comment by dcoplowe** [comment]
Hi Alex,

This isn't a client side error so upgrading shouldn't have done anything. Could you send me an example of the customer details you are passing to the create method? This should help us better understand where things have gone wrong.

**Comment by dcoplowe** [comment]
Closing as support are looking into this.
